apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users  # its a label name which in confgure in users-deployment.yaml file 
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080          #container port